### ISSUE TITLE
Sunset timer does not repeat

### ISSUE THREAD

**Issue by ooswald** [dpjanes/iotdb-timers#1]
This works once but does not repeat. When started _after_ sunset, it never triggers.

```
timers.sunset({
    latitude: 46.93498,
    longitude: 7.441162,
    day_repeat: 1,
    hour: 0,
    delta: 10 * 60,
}, function (event) {
    console.log("SUNTIMER");
});
```

A possible fix seems to be adding this line in sun.js/_recalculate (haven't tested):

```
self.when._dd = _.defaults(self.when._dd, self.paramd);  // may fix it
self._schedule(self.when)
```

**Comment by dpjanes** [comment]
Are you sure? The logic is

1) set a day timer, which will trigger once a day at midnight - "the heartbeat"
2) immediately schedule a sunset event

If (2) is after sunset, it will give the "in the past message". Then at midnight, (1) triggers and schedules the next (2) sunset event, which should work because midnight is before sunset[*]

So you should see a message like this too (which is the heartbeat)

14:20:20.289Z  INFO iotdb-timer: schedule updated (module=timer, method=_scheduler, next_run=47379.71199989319, unique_id=19)

Let me know. I'm going to run it here after sunset and see if actually does do the right thing.

[*] this may be problematic in the arctic

**Comment by dpjanes** [comment]
Thinking out loud, is I should schedule the next sunset at the next sunrise.

**Comment by ooswald** [comment]
Interesting approach, didn't cross my mind to do it this way. I suggest you extend the readme accordingly, would have saved me a couple of hours :D
